name: watermark-vault

services:
  watermark-vault:
    container_name: watermark-vault
    image: ghcr.io/zzm6899/watermark-vault:latest
    restart: unless-stopped
    ports:
      - protocol: tcp
        published: 5066
        target: 5066
    environment:
      - TZ=Australia/Sydney
    volumes:
      - /mnt/your-pool/apps/booking-gal/data:/data
